### ISSUE TITLE
Dropdowns should be styled

### ISSUE THREAD

**Issue by contextlimit** [daftspunk/foundationstrap#2]
I want these dropdowns: http://o7.no/17HS33B

**Comment by daftspunk** [comment]
Custom forms are great. We need to develop a way that respects the native element and keep their styling when the DOM changes. It's a difficult challenge, not sure if anyone has done this right yet. 

The reason for this, I should be able to rip out the custom form plugin and the page should still behave the same (no custom JS required). And vice versa, I should be able to add the custom form plugin and have it magically work without any special JS.

In summary two main requirements I have for this:
- No need to `restyleUI()` on AJAX refresh... plugin should be constantly polling for unstyled elements (efficiently)
- UI elements should respect native events.

Some examples of native element respect: 
- If the value is updated using `val()` the custom control should update it's value. 
- If the `onChange` event is triggered via JS on the original element, the control should mirror this event. 
- If the user triggers the `onChange` event, the custom control should trigger the native element.

I'm very close to writing this myself, the main challenge is the last two points because the logic has a potential infinite loop. 

I think take the look and feel of Foundation 3's controls with the functionality I wrote for PHPR admin module.

**Comment by contextlimit** [comment]
Still love what we built here but gotta clean up my open issues~
